#!/bin/bash

# prerequisites
is_unzip=`command -v unzip`
if [[ -z "$is_unzip" ]] ; then
  echo "can't find command unzip"
  exit -1
fi

# to enable loggin, use command: DEBUG=y uao ...
debug=${DEBUG:-n}
function log {
  message=$1
  if [[ ! -z "$message" ]] ; then
    `test ".$debug" != ".n"` && echo "$message"
  fi
}

archive="$(cd "$(dirname "$1")"; pwd -P)/$(basename "$1")"
log "archive: $archive"
if [[ -z "$archive" ]] ; then
  echo "usage: $0 path/to/archive.zip"
  exit 1
fi

dir=`basename "$archive" .zip`
log "dir: $dir"

if [[ "$dir" == *.zip ]] ; then
  echo "cannot parse directory for $archive arhive"
  exit 2
fi
if [[ -d "$dir" ]] ; then
  echo "directory $dir already exists"
  exit 3
fi

parent="$(dirname "$archive")"
log "parent: $parent"

log "mkdir $parent/$dir"
mkdir "$parent/$dir"

log "unzip -d $parent/$dir $archive"
unzip -d "$parent/$dir" "$archive"

log "idea $parent/$dir/"
idea "$parent/$dir/"
