#!/bin/bash

# to enable loggin, use command: DEBUG=y uao ...
debug=${DEBUG:-n}
function log {
  message=$1
  if [[ ! -z "$message" ]] ; then
    `test ".$debug" != ".n"` && echo "$message"
  fi
}

archive="$(cd "$(dirname "$1")"; pwd -P)/$(basename "$1")"
log "archive: $archive"
if [[ -z "$archive" ]] ; then
  echo "usage: $0 path/to/archive.zip"
  exit 1
fi

base="$(basename -- $1)"
log "base: $base"

extension=${archive##*.}
log "extension: $extension"
if [[ ".$extension" != ".zip" ]] ; then
  echo "only .zip archive is supported"
  exit 2
fi

dir="${archive%.*}"
log "dir: $dir"

if [[ -d "$dir" ]] ; then
  echo "directory $dir already exists"
  exit 3
fi

parent="$(dirname "$archive")"
log "parent: $parent"

log "unzip -d $parent/ $archive"
unzip -d "$parent" "$archive"

log "idea $dir"
idea $dir/

